import io
import json
from datetime import datetime, timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

BRAND_NAVY = colors.HexColor("#0B1120")
BRAND_DARK = colors.HexColor("#0F172A")
BRAND_CYAN = colors.HexColor("#22D3EE")
BRAND_CYAN_LIGHT = colors.HexColor("#67E8F9")
BRAND_AMBER = colors.HexColor("#F59E0B")
BRAND_EMERALD = colors.HexColor("#34D399")
BRAND_SLATE = colors.HexColor("#94A3B8")
BRAND_SLATE_LIGHT = colors.HexColor("#CBD5E1")
BRAND_WHITE = colors.white
BRAND_LIGHT_BG = colors.HexColor("#F1F5F9")

DISCLAIMER = (
    "This report is generated by an AI-based stroke-risk classification system "
    "and is intended for informational and educational purposes only. It is not "
    "a medical diagnosis and should not replace professional medical advice, "
    "diagnosis, or treatment. Consult a qualified healthcare professional for "
    "medical concerns."
)

FIELD_LABELS = {
    "age": "Age",
    "gender": "Gender",
    "hypertension": "Hypertension",
    "heart_disease": "Heart Disease",
    "ever_married": "Ever Married",
    "work_type": "Work Type",
    "residence_type": "Residence Type",
    "avg_glucose_level": "Avg Glucose Level (mg/dL)",
    "bmi": "BMI",
    "smoking_status": "Smoking Status",
}

YES_NO_FIELDS = {"hypertension", "heart_disease"}


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="BrandTitle",
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=BRAND_CYAN,
        alignment=TA_CENTER,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name="BrandSubtitle",
        fontName="Helvetica",
        fontSize=12,
        textColor=BRAND_SLATE,
        alignment=TA_CENTER,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="SectionHead",
        fontName="Helvetica-Bold",
        fontSize=13,
        textColor=BRAND_CYAN,
        spaceBefore=14,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="Body",
        fontName="Helvetica",
        fontSize=10,
        textColor=BRAND_DARK,
        leading=14,
    ))
    styles.add(ParagraphStyle(
        name="BodyBold",
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=BRAND_DARK,
        leading=14,
    ))
    styles.add(ParagraphStyle(
        name="Small",
        fontName="Helvetica",
        fontSize=8,
        textColor=BRAND_SLATE,
        leading=10,
    ))
    styles.add(ParagraphStyle(
        name="SmallCenter",
        fontName="Helvetica",
        fontSize=8,
        textColor=BRAND_SLATE,
        leading=10,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        name="Disclaimer",
        fontName="Helvetica-Oblique",
        fontSize=8,
        textColor=BRAND_SLATE,
        leading=11,
        spaceBefore=10,
    ))
    styles.add(ParagraphStyle(
        name="TableCell",
        fontName="Helvetica",
        fontSize=9,
        textColor=BRAND_DARK,
        leading=12,
    ))
    styles.add(ParagraphStyle(
        name="TableCellBold",
        fontName="Helvetica-Bold",
        fontSize=9,
        textColor=BRAND_DARK,
        leading=12,
    ))
    styles.add(ParagraphStyle(
        name="BigNumber",
        fontName="Helvetica-Bold",
        fontSize=28,
        textColor=BRAND_CYAN,
        alignment=TA_CENTER,
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        name="BigLabel",
        fontName="Helvetica",
        fontSize=9,
        textColor=BRAND_SLATE,
        alignment=TA_CENTER,
        spaceAfter=6,
    ))
    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    canvas.setFillColor(BRAND_NAVY)
    canvas.rect(0, h - 22 * mm, w, 22 * mm, fill=1, stroke=0)
    canvas.setFillColor(BRAND_CYAN)
    canvas.rect(0, h - 22.5 * mm, w, 0.5 * mm, fill=1, stroke=0)

    canvas.setFont("Helvetica-Bold", 14)
    canvas.setFillColor(BRAND_WHITE)
    canvas.drawString(20 * mm, h - 14 * mm, "NEURORISK AI")

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(BRAND_SLATE)
    canvas.drawRightString(w - 20 * mm, h - 14 * mm, "Stroke Risk Assessment Report")

    canvas.setFillColor(BRAND_CYAN)
    canvas.rect(0, 18 * mm, w, 0.3 * mm, fill=1, stroke=0)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(BRAND_SLATE)
    canvas.drawString(20 * mm, 12 * mm, "NeuroRisk AI \u2014 Confidential")
    canvas.drawRightString(w - 20 * mm, 12 * mm, f"Page {doc.page}")

    canvas.restoreState()


def _risk_color(risk_level):
    if risk_level == "High Risk":
        return BRAND_AMBER
    return BRAND_EMERALD


def _build_summary_table(styles, stroke_prob, no_stroke_prob, risk_level):
    rc = _risk_color(risk_level)
    data = [
        [
            Paragraph("Stroke Risk", styles["Small"]),
            Paragraph("No Stroke Probability", styles["Small"]),
            Paragraph("Risk Level", styles["Small"]),
        ],
        [
            Paragraph(f'<font color="#22D3EE"><b>{stroke_prob:.2f}%</b></font>', styles["BodyBold"]),
            Paragraph(f'<b>{no_stroke_prob:.2f}%</b>', styles["BodyBold"]),
            Paragraph(f'<font color="{rc.hexval()}"><b>{risk_level}</b></font>', styles["BodyBold"]),
        ],
    ]
    t = Table(data, colWidths=[55 * mm, 55 * mm, 55 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_LIGHT_BG),
        ("BACKGROUND", (0, 1), (-1, 1), BRAND_WHITE),
        ("BOX", (0, 0), (-1, -1), 0.5, BRAND_SLATE_LIGHT),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, BRAND_SLATE_LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    return t


def _build_patient_table(styles, patient):
    if not patient:
        return Paragraph("No input data available.", styles["Body"])
    rows = []
    for key in ["age", "gender", "hypertension", "heart_disease", "ever_married",
                 "work_type", "residence_type", "avg_glucose_level", "bmi", "smoking_status"]:
        label = FIELD_LABELS.get(key, key)
        val = patient.get(key, "\u2014")
        if key in YES_NO_FIELDS:
            val = "Yes" if val == 1 else "No"
        rows.append([
            Paragraph(label, styles["TableCell"]),
            Paragraph(str(val), styles["TableCellBold"]),
        ])
    t = Table(rows, colWidths=[80 * mm, 85 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), BRAND_LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, BRAND_SLATE_LIGHT),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, BRAND_SLATE_LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def generate_assessment_report(user, assessment, assessment_index=None):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=30 * mm, bottomMargin=25 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )
    styles = _styles()
    story = []

    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph("Stroke Risk Assessment Report", styles["BrandSubtitle"]))
    story.append(Spacer(1, 2 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_CYAN, spaceAfter=8))

    ts = assessment.get("created_at") or ""
    if ts:
        try:
            dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
            date_str = dt.strftime("%B %d, %Y")
            time_str = dt.strftime("%I:%M %p UTC")
        except Exception:
            date_str = ts
            time_str = ""
    else:
        date_str = "\u2014"
        time_str = ""

    idx_label = f"#{assessment_index}" if assessment_index else f"#{assessment.get('id', '')}"

    meta = [
        ["User Name", user.get("name", "\u2014")],
        ["User Email", user.get("email", "\u2014")],
        ["Assessment ID", str(assessment.get("id", "\u2014"))],
        ["Assessment Index", idx_label],
        ["Date", date_str],
    ]
    if time_str:
        meta.append(["Time", time_str])

    meta_rows = [
        [
            Paragraph(r[0], styles["TableCell"]),
            Paragraph(r[1], styles["TableCellBold"]),
        ]
        for r in meta
    ]
    meta_t = Table(meta_rows, colWidths=[60 * mm, 105 * mm])
    meta_t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), BRAND_LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, BRAND_SLATE_LIGHT),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, BRAND_SLATE_LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(Paragraph("User Information", styles["SectionHead"]))
    story.append(meta_t)

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Prediction Result", styles["SectionHead"]))
    stroke_prob = assessment.get("probability", 0)
    no_stroke_prob = assessment.get("no_stroke_probability", round(100 - stroke_prob, 2))
    risk_level = assessment.get("risk_level", "Low Risk")
    story.append(_build_summary_table(styles, stroke_prob, no_stroke_prob, risk_level))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Assessment Input Data", styles["SectionHead"]))
    patient = assessment.get("patient") or {}
    story.append(_build_patient_table(styles, patient))

    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=0.3, color=BRAND_SLATE_LIGHT, spaceAfter=4))
    story.append(Paragraph("Medical Disclaimer", styles["SectionHead"]))
    story.append(Paragraph(DISCLAIMER, styles["Disclaimer"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf


def generate_comparison_report(user, assessments):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=30 * mm, bottomMargin=25 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )
    styles = _styles()
    story = []

    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph("Assessment Comparison Report", styles["BrandSubtitle"]))
    story.append(Spacer(1, 2 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_CYAN, spaceAfter=8))

    now_str = datetime.now(timezone.utc).strftime("%B %d, %Y at %I:%M %p UTC")
    story.append(Paragraph("User Information", styles["SectionHead"]))
    meta_rows = [
        [Paragraph("Name", styles["TableCell"]), Paragraph(user.get("name", "\u2014"), styles["TableCellBold"])],
        [Paragraph("Email", styles["TableCell"]), Paragraph(user.get("email", "\u2014"), styles["TableCellBold"])],
        [Paragraph("Report Generated", styles["TableCell"]), Paragraph(now_str, styles["TableCellBold"])],
        [Paragraph("Total Assessments", styles["TableCell"]), Paragraph(str(len(assessments)), styles["TableCellBold"])],
    ]
    meta_t = Table(meta_rows, colWidths=[60 * mm, 105 * mm])
    meta_t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), BRAND_LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, BRAND_SLATE_LIGHT),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, BRAND_SLATE_LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_t)

    probs = [a.get("probability", 0) for a in assessments]
    lowest = min(probs) if probs else 0
    highest = max(probs) if probs else 0
    avg = sum(probs) / len(probs) if probs else 0

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Summary Statistics", styles["SectionHead"]))
    stats_data = [
        [
            Paragraph("Lowest Risk", styles["Small"]),
            Paragraph("Highest Risk", styles["Small"]),
            Paragraph("Average Risk", styles["Small"]),
            Paragraph("Total", styles["Small"]),
        ],
        [
            Paragraph(f'<font color="#34D399"><b>{lowest:.2f}%</b></font>', styles["BodyBold"]),
            Paragraph(f'<font color="#F59E0B"><b>{highest:.2f}%</b></font>', styles["BodyBold"]),
            Paragraph(f'<b>{avg:.2f}%</b>', styles["BodyBold"]),
            Paragraph(f'<b>{len(assessments)}</b>', styles["BodyBold"]),
        ],
    ]
    stats_t = Table(stats_data, colWidths=[42 * mm, 42 * mm, 42 * mm, 37 * mm])
    stats_t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, BRAND_SLATE_LIGHT),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, BRAND_SLATE_LIGHT),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(stats_t)

    if len(assessments) >= 2:
        story.append(Spacer(1, 3 * mm))
        story.append(Paragraph("Risk Trend", styles["SectionHead"]))
        first_prob = assessments[0].get("probability", 0)
        prev_prob = assessments[1].get("probability", 0)
        delta = first_prob - prev_prob
        if abs(delta) < 0.01:
            trend_text = "Risk stayed approximately the same compared to the previous assessment."
        elif delta > 0:
            trend_text = f"Risk increased by {abs(delta):.2f}% compared to the previous assessment."
        else:
            trend_text = f"Risk decreased by {abs(delta):.2f}% compared to the previous assessment."
        story.append(Paragraph(trend_text, styles["Body"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Assessment History", styles["SectionHead"]))

    total = len(assessments)
    header = ["#", "Assessment ID", "Date", "Stroke Risk", "No Stroke Risk", "Level"]
    table_rows = [header]
    for idx, a in enumerate(assessments):
        ts = a.get("created_at") or ""
        try:
            dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
            date_str = dt.strftime("%b %d, %Y %H:%M")
        except Exception:
            date_str = ts[:16] if ts else "\u2014"
        rc = _risk_color(a.get("risk_level", "Low Risk"))
        table_rows.append([
            str(total - idx),
            str(a.get("id", "\u2014")),
            date_str,
            f'{a.get("probability", 0):.2f}%',
            f'{a.get("no_stroke_probability", 0):.2f}%',
            a.get("risk_level", "\u2014"),
        ])

    col_widths = [12 * mm, 22 * mm, 40 * mm, 30 * mm, 30 * mm, 30 * mm]
    data_cells = []
    for ri, row in enumerate(table_rows):
        cells = []
        for ci, val in enumerate(row):
            if ri == 0:
                cells.append(Paragraph(val, styles["Small"]))
            else:
                style = styles["TableCell"]
                if ci == 4:
                    cells.append(Paragraph(f"<b>{val}</b>", style))
                elif ci == 5:
                    c = _risk_color(val)
                    cells.append(Paragraph(f'<font color="{c.hexval()}">{val}</font>', style))
                else:
                    cells.append(Paragraph(val, style))
        data_cells.append(cells)

    hist_t = Table(data_cells, colWidths=col_widths)
    ts_style = [
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), BRAND_WHITE),
        ("BOX", (0, 0), (-1, -1), 0.5, BRAND_SLATE_LIGHT),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, BRAND_SLATE_LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]
    for ri in range(1, len(data_cells)):
        if ri % 2 == 0:
            ts_style.append(("BACKGROUND", (0, ri), (-1, ri), BRAND_LIGHT_BG))
    hist_t.setStyle(TableStyle(ts_style))
    story.append(hist_t)

    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=0.3, color=BRAND_SLATE_LIGHT, spaceAfter=4))
    story.append(Paragraph("Medical Disclaimer", styles["SectionHead"]))
    story.append(Paragraph(DISCLAIMER, styles["Disclaimer"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf
